# NAME: Joseph Lin
# EMAIL: jj.lin42@gmail.com
# ID: 505111868

default:
	ln run_lab3b lab3b
	chmod u+x lab3b

dist:
	tar -cvzf lab3b-505111868.tar.gz Makefile README lab3b.py run_lab3b

clean:
	rm -f lab3b-505111868.tar.gz lab3b