# NAME: Joseph Lin
# EMAIL: jj.lin42@gmail.com
# ID: 505111868

default:
	gcc -g -o lab1a -Wall -Wextra lab1a.c

clean:
	rm -f lab1a lab1a-505111868.tar.gz

dist: lab1a.c Makefile README
	tar -czvf lab1a-505111868.tar.gz lab1a.c Makefile README